version: '2'

services:

  reporter:
    image: opentraffic/reporter:latest
    networks:
      - opentraffic
    ports:
      - "8003:8003"
    volumes:
      - ${DATAPATH}:/data/valhalla
    environment:
      - MATCHER_LISTEN_PORT=8003
      # - DATASTORE_URL=http://172.17.0.1:8003/store?

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - "zookeeper:zk"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "trace:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  valhalla:
    image: mapzen/valhalla-source:latest
    ports:
      - "8002:8002"
    volumes:
      - ${VALHALLA_DOCKER_DATAPATH}:/data/valhalla
    networks:
      - opentraffic

  reporterqa:
    image: mxndrwgrdnr/reporter-qa:beta
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/notebooks 
    networks:
      - opentraffic
    depends_on:
      - valhalla
      - kafka
      - zookeeper
      - reporter
    links:
     - valhalla
     - reporter

networks:
  opentraffic:
    driver: bridge