version: '2'

services:

  reporter:
    image: opentraffic/reporter:07e14cdc91ae7fa2f7361b25e8ec1b1c2d1c1cc1
    networks:
      - opentraffic
    ports:
      - "8003:8003"
    volumes:
      - ${VALHALLA_DOCKER_DATAPATH}:/data/valhalla
    environment:
      - MATCHER_LISTEN_PORT=8003
    container_name: reporter

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - "zookeeper:zk"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "trace:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka

  valhalla:
    image: valhalla/docker:ppa-1.2.5
    ports:
      - "8002:8002"
    volumes:
      - ${VALHALLA_DOCKER_DATAPATH}:/data/valhalla
    networks:
      - opentraffic
    container_name: valhalla

  reporterqa:
    image: opentraffic/reporter-quality-testing-rig:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/notebooks
      - ./data:/home/data
      - ./validator:/home/validator
    networks:
      - opentraffic
    depends_on:
      - valhalla
      - kafka
      - zookeeper
      - reporter
    links:
      - valhalla
      - reporter
    container_name: reporter-qa
    environment: 
      GOOGLE_MAPS: $GOOGLE_MAPS
      MAPZEN_API: $MAPZEN_API

networks:
  opentraffic:
    driver: bridge
